name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    env:
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          
3306/tcp
  steps:
uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
  with:
    php-version: '8.1'
uses: actions/checkout@v3
name: Copy .env
run: php -r "file_exists('.env') || copy('.env.example', '.env');"
name: Composer Install
run: composer install
name: Key Generate
run: php artisan key:generate
name: Config
run: php artisan config
name: Create database
run: php artisan migrate -v
env:
    DB_PORT: ${{ job.services.mysql.ports['3306'] }}
name: Set Database
run: php artisan set-database
env:
    DB_PORT: ${{ job.services.mysql.ports['3306'] }}
name: Run unit-test via PHPUnit
env:
  DB_CONNECTION: mysql# DB_DATABASE: database/database.sqlite# DB_DATABASE: test# DB_USERNAME: root# DB_PASSWORD: password
  DB_PORT: ${{ job.services.mysql.ports['3306'] }}
run: vendor/bin/phpunit
