name: RecruitmentJob

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Composer Install
        run: composer install

      - name: Key Generate
        run: php artisan key:generate

      - name: Config
        run: php artisan config:clear

      - name: Create database
        run: php artisan migrate -v
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}

      - name: Set Database
        run: php artisan set-database
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}

      - name: Run unit-test via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: test
          DB_USERNAME: root
          DB_PASSWORD: password
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
        run: vendor/bin/phpunit
