name: RecruitmentJob

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Composer Install
        run: composer install

      - name: Key Generate
        run: php artisan key:generate

      - name: Config
        run: php artisan config:clear

      - name: Create database
        run: php artisan migrate -v
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}

      - name: Set Database
        run: php artisan set-database
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}

      - name: Create test database
        run: |
          php artisan config:clear
          php artisan migrate -v --database=testing --env=testing
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}

      - name: Run unit-test via PHPUnit
        env:
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: password
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
        run: vendor/bin/phpunit

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{ secrets.MAIL_USERNAME }}
            password: ${{ secrets.MAIL_PASSWORD }}
            subject: GitHub Actions result
            to: tranlequangthinh24122002@gmail.com
            from: Your Name <your-email@gmail.com>
            body: |
              The workflow has completed. Check the details at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        if: always()
